"""Update database

Revision ID: a56e3d931382
Revises: 32e2d3182f2f
Create Date: 2019-10-22 11:12:12.423586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a56e3d931382'
down_revision = '32e2d3182f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pitches', sa.Column('comments_id', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('description', sa.String(), nullable=True))
    op.add_column('pitches', sa.Column('dislike', sa.Integer(), nullable=True))
    op.add_column('pitches', sa.Column('like', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'comments', ['comments_id'], ['id'])
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pass_secure', sa.String(length=225), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_pitch_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_pitch_id_fkey', 'users', 'pitches', ['pitch_id'], ['id'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'pass_secure')
    op.drop_column('users', 'email')
    op.drop_column('users', 'bio')
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'like')
    op.drop_column('pitches', 'dislike')
    op.drop_column('pitches', 'description')
    op.drop_column('pitches', 'comments_id')
    op.drop_table('comments')
    # ### end Alembic commands ###
